email: your-email@domain.com

exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/stylesheets
  style: :compressed

title: "Brad Dougherty"
tagline: ""
description: "Follow <a href=\"https://micro.blog/bdougherty\">@bdougherty on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/bdougherty\">@bdougherty on Micro.blog</a>."
baseurl: ""
url: "https://bdougherty.micro.blog"
markdown: "kramdown"
username: "bdougherty"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Brad Dougherty"
name: "Brad Dougherty"
gravatar_hash: "95f937c781b55dc676a94a9bc46473d7"
avatar: "https://micro.blog/bdougherty/avatar.jpg"
full_name: "Brad Dougherty"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "210"